import csv
from ciudadano import Ciudadano
import random
import os

def generar_nombres(num):
    nombres = [
        "Juan",
        "Maria",
        "Luis",
        "Ana",
        "Hugo",
        "Mateo",
        "Martín",
        "Lucas",
        "Leo",
        "Daniel",
        "Alejandro",
        "Manuel",
        "Pablo",
        "Álvaro",
        "Adrián",
        "Enzo",
        "Mario",
        "Diego",
        "David",
        "Oliver",
        "Marcos",
        "Thiago",
        "Marco",
        "Álex",
        "Javier",
        "Izan",
        "Bruno",
        "Miguel",
        "Antonio",
        "Gonzalo",
        "Liam",
        "Gael",
        "Marc",
        "Carlos",
        "Juan",
        "Ángel",
        "Dylan",
        "Nicolás",
        "José",
        "Sergio",
        "Gabriel",
        "Luca",
        "Jorge",
        "Darío",
        "Íker",
        "Samuel",
        "Eric",
        "Adam",
        "Héctor",
        "Francisco",
        "Rodrigo",
        "Jesús",
        "Erik",
        "Amir",
        "Jaime",
        "Ian",
        "Rubén",
        "Aarón",
        "Iván",
        "Pau",
        "Víctor",
        "Guillermo",
        "Luis",
        "Mohamed",
        "Pedro",
        "Julen",
        "Unai",
        "Rafael",
        "Santiago",
        "Saúl",
        "Alberto",
        "Noah",
        "Aitor",
        "Joel",
        "Nil",
        "Jan",
        "Pol",
        "Raúl",
        "Matías",
        "Martí",
        "Fernando",
        "Andrés",
        "Rayan",
        "Alonso",
        "Ismael",
        "Asier",
        "Biel",
        "Ander",
        "Aleix",
        "Axel",
        "Alan",
        "Ignacio",
        "Fabio",
        "Neizan",
        "Jon",
        "Teo",
        "Isaac",
        "Arnau",
        "Luka",
        "Max",
        "Imran",
        "Youssef",
        "Anas",
        "Elías",
    ]
    apellidos = [
        "Perez",
        "Gomez",
        "Rodriguez",
        "Fernandez",
        "Abaigar",
        "Adei",
        "Adur",
        "Adiran",
        "Aimar",
        "Aitor",
        "Andoni",
        "Ander",
        "Antxon",
        "Amets",
        "Aratz",
        "Argi",
        "Aritz",
        "Asier",
        "Balkoe",
        "Baltz",
        "Bazkoare",
        "Beltso",
        "Bernat",
        "Beñat",
        "Bikendi",
        "Biktor",
        "Bizen",
        "Dabi",
        "Dari",
        "Damen",
        "Diagur",
        "Dunixi",
        "Eako",
        "Eder",
        "Edorta",
        "Edur",
        "Eki",
        "Ekaitz",
        "Eladi",
        "Elixi",
        "Eloi",
        "Emiri",
        "Eneko",
        "Endrike",
        "Eritz",
        "Etor",
        "Euken",
        "Ferran",
        "Frantzisko",
        "Ganiz",
        "Gari",
        "Gentzen",
        "Gergori",
        "Gilem",
        "Gizon",
        "Goiznabar",
        "Gontzal",
        "Gorka",
        "Grazian",
        "Guren",
        "Haize",
        "Haran",
        "Haritz",
        "Heiko",
        "Hodei",
        "Ibai",
        "Ibar",
        "Igon",
        "Igor",
        "Iker",
        "Imanol",
        "Iñaki",
        "Ipar",
        "Irai",
        "Iren",
        "Izan",
        "Izei",
        "Jon",
        "Jeino",
        "Joritz",
        "Josu",
        "Julen",
        "Jurgi",
        "Kai",
        "Kasi",
        "Kauldi",
        "Kutun",
        "Lain",
        "Luken",
        "Maide",
        "Mairu",
        "Maren",
        "Markel",
        "Martitz",
        "Mikel",
        "Negu",
        "Neketi",
        "Nikanor",
        "Odei",
        "Oier",
        "Oihan",
        "Orentzi",
        "Orixe",
        "Ortzadar",
        "Ostertz",
        "Paken",
        "Patxi",
        "Roke",
        "Sanduru",
        "Semenko",
        "Sendoa",
        "Silban",
        "Sukil",
        "Todor",
        "Txarles",
        "Ugutz",
        "Uhaitz",
        "Unai",
        "Untzalu",
        "Urtzi",
        "Uztai",
        "Xabier",
        "Zuhaitz",
        "Zuri",
        "Zuzen",
    ]

    os.makedirs('datos', exist_ok=True)

    with open("datos/ciudadanos.csv", mode="w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["id", "nombre", "apellido"])
        for i in range(num):
            writer.writerow(
                [i, nombres[i % len(nombres)], apellidos[i % len(apellidos)]]
            )

def cargar_ciudadanos(archivo_csv, num_ciudadanos, comunidad):
    ciudadanos = []
    with open(archivo_csv, mode="r") as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            if len(ciudadanos) >= num_ciudadanos:
                break
            ciudadano = Ciudadano(
                id=int(row["id"]),
                nombre=row["nombre"],
                apellido=row["apellido"],
                comunidad=comunidad
            )
            ciudadanos.append(ciudadano)
    return ciudadanos


